JOB_TITLES = [
    "Full Stack Developer",
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Python Developer",
    "Mobile Developer",
    "Network Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Site Reliability Engineer",
    "API Developer",
    "Systems Engineer",
]

COUNTRIES = [
    {"code": "IT", "city": "Pisa", "full": "Italy"},
    {"code": "DE", "city": "Berlin", "full": "Germany"},
    {"code": "NL", "city": "Amsterdam", "full": "Netherlands"},
    {"code": "GB", "city": "London", "full": "United Kingdom"},
    {"code": "FR", "city": "Paris", "full": "France"},
    {"code": "ES", "city": "Barcelona", "full": "Spain"},
    {"code": "SE", "city": "Stockholm", "full": "Sweden"},
    {"code": "NO", "city": "Oslo", "full": "Norway"},
    {"code": "CH", "city": "Zurich", "full": "Switzerland"},
    {"code": "BE", "city": "Brussels", "full": "Belgium"},
    {"code": "PL", "city": "Warsaw", "full": "Poland"},
    {"code": "PT", "city": "Lisbon", "full": "Portugal"},
]

DEFAULT_SITES = ["linkedin"]

DEFAULT_SHEET_HEADERS = [
    "Job Title",
    "Company",
    "Location",
    "Employment Type",
    "Seniority",
    "Salary Range",
    "Applicants",
    "Posted",
    "Apply Link",
    "Company URL",
    "Job Summary",
    "AI Fit",
    "Resume Doc",
    "Fit Score",
    "Recommendation",
    "Decision",
    "Reasoning",
    "Missing Skills",
    "Candidate Highlights",
    "Resume Focus",
    "Resume Summary",
    "Resume Path",
    "Cover Letter Path",
    "Email Intro Path",
    "Source Site",
    "Search Title",
    "Search Country",
    "Run ID",
    "Searched At",
]
